apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  generation: 1
  name: netapp-trident
  labels:
    vendor: netapp
spec:
  conclusion: You can manage your stateful applications requiremeents with the NetApp data managemetn capabilities.
  description: Install Trident to manage persistent storage with the NetApp Data Management capabilities.
  displayName: Deploy NetApp Trident Container Storage Interface. 
  durationMinutes: 20
  icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAwIDkwOS4wOTEiIHhtbDpzcGFjZT0icHJlc2VydmUiIHdpZHRoPSIyNDAwIiBoZWlnaHQ9IjE4MTAiPgogIDxwYXRoIGQ9Ik03ODcuODc5IDQzNC41NDVoMTYuODE4djguNDg1YzQuMDkxLTUuNDU1IDkuNjk3LTkuNTQ1IDE4LjQ4NS05LjU0NSAxMy43ODggMCAyNi45NyAxMC43NTggMjYuOTcgMzAuNjA2di4xNTJjMCAxOS44NDgtMTIuODc5IDMwLjYwNi0yNi45NyAzMC42MDYtOC45MzkgMC0xNC41NDUtNC4wOTEtMTguNDg1LTguNzg4djI1LjQ1NWgtMTYuODE4em00NS40NTUgMjkuNjk3di0uMTUyYzAtOS44NDgtNi42NjctMTYuMzY0LTE0LjU0NS0xNi4zNjRzLTE0LjM5NCA2LjUxNS0xNC4zOTQgMTYuMzY0di4xNTJjMCA5Ljg0OCA2LjUxNSAxNi4zNjQgMTQuMzk0IDE2LjM2NHMxNC41NDUtNi4zNjQgMTQuNTQ1LTE2LjM2NG0tMzc4LjkzOS00OC4zMzNoMTUuNzU4bDM2LjIxMiA0OC4xODJ2LTQ4LjE4MmgxNi44MTh2NzcuODc5aC0xNC41NDVsLTM3LjQyNi00OS4yNDN2NDkuMjQyaC0xNi44MTh6bTc2Ljk3IDQ4LjYzNnYtLjE1MmMwLTE2Ljk3IDEyLjEyMS0zMC43NTggMjkuMjQyLTMwLjc1OCAxOS44NDggMCAyOC43ODggMTUuMzAzIDI4Ljc4OCAzMi4xMjEgMCAxLjM2NC0uMTUyIDIuODc5LS4xNTIgNC4zOTRoLTQxLjIxMmMxLjY2NyA3LjU3NiA2Ljk3IDExLjY2NyAxNC41NDUgMTEuNjY3IDUuNjA2IDAgOS42OTctMS44MTggMTQuMzk0LTYuMDYxbDkuNTQ1IDguNDg1Yy01LjQ1NSA2LjgxOC0xMy40ODUgMTEuMDYxLTI0LjI0MiAxMS4wNjEtMTcuODc5LS4xNTItMzAuOTA5LTEyLjcyNy0zMC45MDktMzAuNzU4bTQxLjY2Ny01Yy0xLjA2MS03LjU3Ni01LjQ1NS0xMi41NzYtMTIuNDI0LTEyLjU3NnMtMTEuNTE1IDUtMTIuODc5IDEyLjU3NnptMjYuOTcgMTcuNDI0di0yOC4wM2gtNy4xMjF2LTE0LjM5NEg2MDB2LTE1LjE1MmgxNi42Njd2MTUuMTUyaDEzLjkzOXYxNC4zOTRoLTEzLjkzOXYyNS4zMDNjMCAzLjkzOSAxLjY2NyA1Ljc1OCA1LjQ1NSA1Ljc1OCAzLjAzIDAgNS45MDktLjc1OCA4LjMzMy0yLjEyMXYxMy40ODVjLTMuNDg1IDIuMTIxLTcuNTc2IDMuNDg1LTEzLjMzMyAzLjQ4NS0xMC4xNTItLjE1Mi0xNy4xMjEtNC4yNDItMTcuMTIxLTE3Ljg3OW0xMTguOTM5LTQyLjQyNGgxNi44MTh2OC40ODVjNC4wOTEtNS40NTUgOS42OTctOS41NDUgMTguNDg1LTkuNTQ1IDEzLjc4OCAwIDI2Ljk3IDEwLjc1OCAyNi45NyAzMC42MDZ2LjE1MmMwIDE5Ljg0OC0xMi44NzkgMzAuNjA2LTI2Ljk3IDMwLjYwNi04LjkzOSAwLTE0LjU0NS00LjA5MS0xOC40ODUtOC43ODh2MjUuNDU1SDcxOC45NHptNDUuMzAzIDI5LjY5N3YtLjE1MmMwLTkuODQ4LTYuNjY3LTE2LjM2NC0xNC41NDUtMTYuMzY0cy0xNC4zOTQgNi41MTUtMTQuMzk0IDE2LjM2NHYuMTUyYzAgOS44NDggNi41MTUgMTYuMzY0IDE0LjM5NCAxNi4zNjQgOC4wMyAwIDE0LjU0NS02LjM2NCAxNC41NDUtMTYuMzY0bS05Ny4xMjEtNDguNDg1aDE1LjMwM2wzMi4yNzMgNzcuODc5SDY5Ni45N2wtNy4xMjEtMTcuNDI0aC0zMC43NThsLTcuMTIxIDE3LjQyNGgtMTcuMjczem0xNy43MjcgNDUuNjA2LTEwLjMwMy0yNS4xNTItMTAuMzAzIDI1LjE1MnptLTM1Ny41NzYtNDUuNDU1djc3Ljg3OWgzNi4zNjRWNDQ2Ljk3aDIwLjc1OHY0Ni44MThoMzYuMzY0di03Ny44Nzl6Ii8+Cjwvc3ZnPgo=
  introduction: |- 
    ### Deploy NetApp Trident Container Storage Interface
    For additional information, see the [NetApp Trident documentation](https://docs.netapp.com/us-en/trident/trident-get-started/intro.html).
  nextQuickStart:
  - netapp-trident-protect
  tasks:
  - description: |-
      To deploy the Trident Protect Operator:

      1. Click on [Operators]{{`{{highlight qs-nav-operators}}`}} and then click on **OperatorHub**.

      2. From the **OperatorHub** catalog, filter down the items by typing **netapp**, and click on the tile called **NetApp Trident**. 
        Acknolwedge the **Community Operator** message. 
      
      3. Click **Install** to open the installation wizard. The default settings are fitting most of the requirements, then click **Install**.

      4. The Trident Operator installation process will start. Once completed, a **green** check mark will appear. Click on **View Operator** to open Trident Operator details.

      **Note**: The Trident Operator can also be deployed using a Helm Charts or a descriptive YAML file, e.g. :
      ```YAML
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: trident-operator
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: trident-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
        startingCSV: trident-operator.v24.10.0
      ```
      Refer to the [NetApp Trident documentation](https://docs.netapp.com/us-en/trident/trident-get-started/intro.html) for more information.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        #### To verify the operator was successfully created:
        1. Do you see a **green** check mark?
        2. Do you have access to the Trident Operator details?
    summary:
      failed: Try the steps again.
      success: You deployed the Netpp Trident Operator!
    title: Install the Trident Operator
  - description: |-
      The Trident Orchestrator is the main component of the Trident suite. It is responsible for managing the storage resources and providing a unified interface to the storage systems. 
      
      To deploy the Trident Orchestrator:

      1. Click [Operators]{{`{{highlight qs-nav-operators}}`}}, then **Installed Operators**, and select **NetApp Trident** from the list. 
      2. From the Trident Operator details page, click the **Trident Orchestrator** tab.
      3. To verify the Trident Orchestrator deployment, click [Workloads]{{`{{highlight qs-nav-workloads}}`}}, then **Pods**.  
      Either filter down the list using the **Project** dropdown menu with the **trident** namespace or search for **trident-controller** in the search bar. 
      
      If deployed successfully, all the Pods should be in **Running** status. 

      **Note**: The Trident Orchestrator can also be deployed using a descriptive YAML file, e.g. :
      ```YAML
      apiVersion: trident.netapp.io/v1
      kind: TridentOrchestrator
      metadata:
        name: trident
        namespace: trident
      spec:
        IPv6: false
        debug: true
        enableNodePrep: true
        imagePullSecrets: []
        imageRegistry: ''
        k8sTimeout: 30
        kubeletDir: /var/lib/kubelet
        namespace: trident
        silenceAutosupport: false
      ```
      Refer to the [NetApp Trident documentation](https://docs.netapp.com/us-en/trident/trident-get-started/intro.html) for more information.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        #### To verify the build is complete:
        Do you see the Trident Orchestrator Pods in **Running** status within the **trident** namespace?
    summary:
      failed: Try the steps again.
      success: All the NetApp Trident Protect CRS are now deployed!
    title: Deploy a Trident Orchestrator
  - description: |-
      A Trident Backend configuration is required to manage the storage resources by connecting to the NetApp storage systems. In this example a NAS driver will be used to create Persistent Volumes with the NFS protocol. For other drivers like SAN, refer to the [NetApp Trident documentation](https://docs.netapp.com/us-en/trident/trident-get-started/intro.html).
      
      It requires the following information:
      1. Credentials to access the storage system.
      2. The NetApp storage system details like data LIF, SVM name, and protocol.

      To create a Trident Backend configuration:
      1. Create a **Secret** with the storage system credentials. Click on [Import]{{`{{highlight qs-masthead-import}}`}}, then insert a YAML definition like the following with necessary modification to fit your environment:  

      ```YAML
      apiVersion: v1
      kind: Secret
      metadata:
        name: trident-svm-credentials
        namespace: trident
      type: Opaque
      stringData:
        username: vsadmin
        password: 234TridentSVM
      ```
      **Note**: The Secret needs to be created with the same namespace as the Trident Orchestrator. Record the Secret name for the next step.

      2. Create a **TridentBackendConfig** with the storage system details. Click on [Import]{{`{{highlight qs-masthead-import}}`}}, then insert a YAML definition like the following with necessary modification to fit your environment:  

      ```YAML
      apiVersion: trident.netapp.io/v1
      kind: TridentBackendConfig
      metadata:
        name: trident-ontap-nas
        namespace: trident
      spec:
        version: 1
        backendName: ontap-nas
        storageDriverName: ontap-nas
        svm: fsx
        managementLIF: 10.0.0.154
        dataLIF: 10.0.0.154
        credentials:
          name: trident-svm-credentials
      ```
      2. Access the [TridentBackendConfig](api-resource/all-namespaces/trident.netapp.io~v1~TridentBackendConfig/instances) page to verify the configuration.
      3. Click on the TridentBackendConfig that was just created and verify that a **Bound** check mark is displayed next to the resource name, here: **trident-ontap-nas**.      

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        Do you see the Secret details page open for **trident-svm-credentials**?
        Do you see the **Bound** check mark next to the TridentBackendConfig resource name? 
    summary:
      failed: Try the steps again.
      success: Congratulations, you now have access to your NetApp storage system!
    title: Create a Trident Backend configuration
  - description: |-
      ### Create a StorageClas:
      1. Click on [Import]{{`{{highlight qs-masthead-import}}`}}, then insert a YAML definition like the following with necessary modification to fit your environment:  

      ```YAML
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
          name: trident-ontap-nas
      provisioner: csi.trident.netapp.io
      parameters:
          backendType: ontap-nas
          clones: 'true'
          fsType: ext4
          snapshots: 'true'
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      ```
      **Notes**: 
      - The StorageClass name provides the minimum configuration to create expandable Persistent Volume using the NAS driver, with the ability to create clones and snapshots.
      - The StorageClass is not set as the default one. If you want to set it as the default, add the following lines within the `metadata` section: 
      ```
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      ```
      However, if there is already a default StorageClass, you will need to manually set the default status to `false` for the existing one.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        #### To verify the StorageClass was successfully created:
        Do you see the StorageClass details page open for **trident-ontap-nas** or within the StorageClass list?
    summary:
      failed: Try the steps again.
      success: You have created a StorageClass using the Trident NAS driver.
    title: Create a StorageClass with Trident
  - description: |-
      ### Create a StorageClas:
      1. Click on [Storage]{{`{{highlight qs-nav-storage}}`}}, then **PersistentVolumeClaims**. 
      2. Click on **Create PersistentVolumeClaim** to open the creation form.
      3. Select the **trident-ontap-nas** StorageClass from the dropdown menu.
      4. Fill in the form with the following information:
        - **Name**: *trident-pvc*  
        - **Access Mode**: *ReadWriteOnce*  
        - **Storage**: *1Gi*  
        - **Volume Mode**: *Filesystem*  

      then Click **Create** to create the PersistentVolumeClaim.

      To verify the PersistentVolumeClaim was successfully created:
      - check the PersistentVolumeClaim details page should be displayed a **Bound** status next to the resource name, here **trident-pvc**.
      - scroll down to observe the details of the associated **StorageClass** and **PersistentVolume** name which should display an output similar to `pvc-4fe2dd6e-cfde-455f-a2a2-778ba6f36cd8`.

      The PersistentVolumeClaim can now be delete as we verified the StorageClass creation.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        #### To verify the StorageClass was successfully created:
        Do you see a **Bound** check mark next to the resource name of the PersistentVolumeClaim?  
        Do you see **trident-ontap-nas** as the associated StorageClass in the PersistentVolumeClaim volume details?
    summary:
      failed: Try the steps again.
      success: Congratulations, Persistent Volumes can now be provisioned using the NetApp Trident Container Storage Interface.
    title: Create a test PersistentVolumeClaim with Trident