apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: {{ .Values.plugin.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "susanoo.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.plugin.port }}-tcp
      protocol: TCP
      port: {{ .Values.plugin.port }}
      targetPort: {{ .Values.plugin.port }}
  selector:
    {{- include "susanoo.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
